__author__ = 'tcezard'


def parse_bamtools_stats(bamtools_stats):
    """Parse the stat file generated by bamtools.
    :param bamtools_stats the text file generated by bamtools
    :return a tuple of 4 integers: total_reads, mapped_reads, duplicate_reads, proper_pairs
    """
    with open(bamtools_stats) as open_file:
        for line in open_file:
            sp_line = line.strip().split()
            if line.startswith('Total reads:'):
                total_reads = int(sp_line[2])
            elif line.startswith('Mapped reads:'):
                mapped_reads = int(sp_line[2])
            elif line.startswith('Duplicates:'):
                duplicate_reads = int(sp_line[1])
            elif line.startswith("'Proper-pairs':"):
                proper_pairs = int(sp_line[1])
    return total_reads, mapped_reads, duplicate_reads, proper_pairs
